stages:
  - runtests
  - deploy

test2.7:
  stage: runtests
  image: python:2.7
  script:
    - echo "Running tests on Python 2.7\n"
    - pip install -r requirements.txt
    - nosetests -vd --with-coverage
    - bash <(curl -s https://codecov.io/bash)
  except:
  - master

test3.5:
  stage: runtests
  image: python:3.5
  script:
    - echo "Running tests on Python 3.5\n"
    - pip install -r requirements.txt
    - nosetests -vd --with-coverage
    - bash <(curl -s https://codecov.io/bash)
  except:
  - master

deploy_to_production:
  stage: deploy
  image: ubuntu:14.04
  script:
    # install rsync
    - 'which rsync || ( apt-get update -y && apt-get install -y rsync )'
    # install ssh-agent
    - 'which ssh-agent || ( apt-get install openssh-client -y )'
    # run ssh-agent
    - eval $(ssh-agent -s)
    # add ssh key stored in SSH_KEY variable to the agent store
    - ssh-add <(echo "$SSH_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "Deploy to staging server\n"
    - rsync -avz -e 'ssh' /builds/danidee/Votr --recursive --exclude="*.env" $ROOT_DIRECTORY
    - echo 'Running migrations if any...'
    - ssh $SSH_REMOTE 'python Votr/migrate.py'
  environment:
    name: production
  only:
  - master
  when: manual
